### ISSUE TITLE
変更箇所

### ISSUE THREAD

**Issue by irishkooky** [riefuchi220/engage_corp#2]
## 変更箇所(現在はXD上に反映されている) 
- TOPページの画像、文言が一部変更
- 社員対談2ページ文言などがざっくり変更
- ベースのフォントサイズを17pt→16ptに変更(17pxがあったら16pxに変更)
- 採用フローが1つ追加
- 似顔絵単体で使われている箇所ですが、「○」有無の使用ですが、「○」見た目の解像度いい方を使用検討しております！

## URL
- 1ページ目：~/recruit-about.html
- 2ページ目：~/interview-01.html
- 3ページ目：~/interview-02.html
- 4ページ目：~/recruit-info.html

**Comment by riefuchi220** [comment]
@irishkooky 
2点修正しました！
横並びは320pxまでは横並びになるようにwidht指定して調整しています。

**Comment by irishkooky** [comment]
@riefuchi220 
ありがと！確認した！
いい感じなのだが、さらに高みへ！というところで1点！

<img width="730" alt="スクリーンショット 2022-06-29 0 19 31" src="https://user-images.githubusercontent.com/77531587/176217302-ad269be1-3069-48b5-a6b3-c9973e5d6119.png">
テキストもう少し広げられる？

https://xd.adobe.com/view/83dacca4-2ce3-4341-804b-6dbc3fad14cd-d689/screen/c165e76c-99c8-423a-b08d-e83d03bc6269/specs/

**Comment by riefuchi220** [comment]
<img width="327" alt="スクリーンショット 2022-06-29 7 05 14" src="https://user-images.githubusercontent.com/72483292/176308446-b35969a4-c3cf-4549-b3ea-e381700c2cd6.png">

これline-height調整したら縦に伸びている感じが少しなくなって良いかなと思い調整しました！

**Comment by riefuchi220** [comment]
わかるところの修正完了しました！

以下の2点が修正内容がわからず....mmmmm

PC
前半
画像が、後編と同じものになっています、、、

後半
大変申し訳ないのですが、前編と同じ幅、大きさ、にしていただけたりしますでしょうか、、、、

**Comment by irishkooky** [comment]
> PC
前半
画像が、後編と同じものになっています、、、

画像が前編と後編で若干違うんだよね笑笑(ほぼアハ体験の世界w)
デザイナーのこだわりでもありそうだから直してあげよう。
<img width="1073" alt="スクリーンショット 2022-07-03 11 39 01" src="https://user-images.githubusercontent.com/77531587/177022342-424b4282-28e6-4251-b1d8-1fb63ae7d327.png">
<img width="907" alt="スクリーンショット 2022-07-03 11 39 19" src="https://user-images.githubusercontent.com/77531587/177022348-7f2e58ce-d619-4021-a922-1c7579d2adff.png">

> PC
前半
画像が、後編と同じものになっています、、、
<img width="811" alt="スクリーンショット 2022-07-03 11 37 34" src="https://user-images.githubusercontent.com/77531587/177022386-6e8c829d-2c3c-4c56-8fd6-2373808a04df.png">

<img width="811" alt="スクリーンショット 2022-07-03 11 37 34" src="https://user-images.githubusercontent.com/77531587/177022397-4f02e06e-66f5-4ddd-9a9d-d92a60ee13af.png">

ボタンの大きさが若干違うのと、あと比較したら分かるんだけどオレンジの縦の長さが若干違うんだよね。右下の画像のサイズを前編後編統一したらいけそうかも！

ボタンに関してはheight固定してあげてもいいかもね👍
