### ISSUE TITLE
ヘッダーのheignt・ホバー挙動の修正

### ISSUE THREAD

**Issue by irishkooky** [riefuchi220/engage_corp#7]
## height修正
<img width="954" alt="スクリーンショット 2022-07-05 0 18 35" src="https://user-images.githubusercontent.com/77531587/177182902-d77b0c36-dbe5-42a6-b65d-90918c771dda.png">

- 下の余白が余分に入ってしまっている。
- heightの指定を削除すればちょうど良くなりそう。

## ホバー挙動の修正
https://user-images.githubusercontent.com/77531587/177183223-3e0c61b9-4423-45d9-864f-729f89e1be2f.mov

- こんな感じで、ホバー時に下線が出てくるように参照→https://www.nxworld.net/css-hover-underline-animation-examples-and-sass-mixin.html#Center
- 下線の色は#f26021で！

**Comment by irishkooky** [comment]
<img width="1194" alt="スクリーンショット 2022-07-05 23 49 54" src="https://user-images.githubusercontent.com/77531587/177357208-211b0b37-4295-44c3-b40f-ada5d0737d55.png">

- headerが小さくなった分キービジュアルのpadding-topを少し縮めてほしい！(微妙な隙間)

**Comment by riefuchi220** [comment]
すみません！余白でないように調整しました！

**Comment by irishkooky** [comment]
solved
