### ISSUE TITLE
ボタンの余白修正

### ISSUE THREAD

**Issue by irishkooky** [riefuchi220/engage_corp#9]
<img width="708" alt="スクリーンショット 2022-07-05 0 37 24" src="https://user-images.githubusercontent.com/77531587/177185679-16e7aab9-5e74-46c5-8680-0685a3f2a9b8.png">

- line-heightが1.8のため、paddingの数字以上に余白が入ってしまう。→line-heightを計算した上で余白が20pxになるようにpaddingを設定

**Comment by riefuchi220** [comment]
修正完了しました！

**Comment by irishkooky** [comment]
<img width="1134" alt="スクリーンショット 2022-07-05 23 53 36" src="https://user-images.githubusercontent.com/77531587/177356922-d55555a1-e65a-4cf7-8ef5-4b97e5efe998.png">

- PC版の方の余白もちょっと大きいかも！
- https://xd.adobe.com/view/0453c77e-6794-48c9-a00d-2d46241e1c3f-5100/specs/

**Comment by irishkooky** [comment]
solved
